### ISSUE TITLE
only use pure as3 in the library

### ISSUE THREAD

**Issue by wangchyz** [artman/Flow#6]
I think a pure as3 version maybe useful.
Could you share us the reason of whu you choose the flex?

**Comment by wangchyz** [comment]
It seems Flow only use a little flex specially,why not just pure as3?
Just a suggestion, waiting you comment, thank you

**Comment by artman** [comment]
There's nothing inherently "Flex" in Flow. You could create a pure AS3 project and use Flow's classes. Just have your main class extend Applciation and you're ready to go. If you use it that way, you don't need to include the Flex library at all.

However, Flow is best when used in combination with MXML, as it's MUCH easier to describe your UI in a declarative language than pure ActionScript. Using MXML adds almost nothing to your SWF size, as MXML is converted into AS3 by MXMLC. Using MXML is my prefered way of working and it should be yours, too. Just trust me, it's far more productive.

The reason why I use the Flex Framework is Binding and Flex Builder IDE support. The Flex Framework automatically registers event listeners when you do something like text="{model.data}" which again is a huge time saver. Also, Flow uses the same namespace for some classes  (e.g. mx.states.*), as these are hard-coded into the Flash Builder IDE. By using the name space Flow can utilize some of the great IDE and MXMLC functionality such as beeing able to use the states-drop-down when creating MXML components to show properties that affect a specific state, or have the compiler report ans error if you have created a skin that lacks a required skinpart.

Essentially, Flow ONLY uses the BindingUtils from the Flex Framework and they weigh only some 20kb. It might be possible to re-created these classes aswell, but that would be a big undertaking and I'm not sure any custom implementation would actually be any faster or weigh less.

Why do you think there should be a pure AS3 version of Flow?

**Comment by wangchyz** [comment]
I think the biggest benefit of using Flash builder is WYSIWYG, but Flow can be used in text editor mode only.
The MXML can be easy repleaced by xml layout file like https://github.com/minimalcomps/minimalcomps/blob/master/src/com/bit101/utils/MinimalConfigurator.as. And There are some other bind utils can be used in as3, like BindLite.

I like Flex, but Flow can only get a little benefit from Flash builder and Flex framework, and a pure as3 version can be fit for more application context. So I think a pure as3 version of Flow maybe more useful.

From you say, "By using the name space Flow can utilize some of the great IDE and MXMLC functionality", Could please talk more about it.

**Comment by artman** [comment]
You're right, I havent found a way to enable design mode in Flash Builder, but would love to if it were possible.
However, why would you want to use MinimalConfigurator, when you can do the same (and much, much more) via MXML? As I said, MXML doesn't add anything to the SWF size and it's an excellent language to describe your UI elements. And sure you can use BindLite, but you'll still need to use a lot more code than what with MXML's binding instructions.

I haven't added any specific examples in the example-project yet, but Flow supports easy and Flex-like component skinning with Skin parts and states. As it uses the same namespace for states, Flow can utilize Flex-features such as state-based visibility control (includeIn- and excludeFrom-properties or changing property-values for different states (like alpha=1, alpha.down=0.5, alpha.disabled=0.2)) without actually including any Flex framework classes in your SWF. And because Flash Builder actually thinks you're creating a Flex app, you'll be able to use the states-dropdown to see which components are included for which states and how states affect different properties.
